In [1]:
import numpy as np

In [3]:
mat = np.array(range(81)).reshape((9, -1))

In [4]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [8]:
np.rot90(mat[1:, :].reshape((-1, 8)), k=3)

array([[73, 65, 57, 49, 41, 33, 25, 17,  9],
       [74, 66, 58, 50, 42, 34, 26, 18, 10],
       [75, 67, 59, 51, 43, 35, 27, 19, 11],
       [76, 68, 60, 52, 44, 36, 28, 20, 12],
       [77, 69, 61, 53, 45, 37, 29, 21, 13],
       [78, 70, 62, 54, 46, 38, 30, 22, 14],
       [79, 71, 63, 55, 47, 39, 31, 23, 15],
       [80, 72, 64, 56, 48, 40, 32, 24, 16]])

In [11]:
np.concatenate([mat[0:1,:], np.rot90(mat[1:, :].reshape((-1, 8)), k=3)])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [73, 65, 57, 49, 41, 33, 25, 17,  9],
       [74, 66, 58, 50, 42, 34, 26, 18, 10],
       [75, 67, 59, 51, 43, 35, 27, 19, 11],
       [76, 68, 60, 52, 44, 36, 28, 20, 12],
       [77, 69, 61, 53, 45, 37, 29, 21, 13],
       [78, 70, 62, 54, 46, 38, 30, 22, 14],
       [79, 71, 63, 55, 47, 39, 31, 23, 15],
       [80, 72, 64, 56, 48, 40, 32, 24, 16]])

In [32]:
def spiral_visit(mat):
    rows, cols = mat.shape
    if rows < 1 or cols < 1:
        return mat
    top_row = mat[0:1, :]
    rest = mat[1:, :]
    assert rest.shape == (rows - 1, cols), f'{rest.shape=}'
    rest = np.rot90(rest.reshape(-1, cols - 1), k=3)
    right_col = rest[:, -1:]
    rest = rest[:, :-1]
    assert rest.shape == (rows - 1, cols - 1), f'{rest.shape=}'
    rest = np.rot90(rest, k=3)
    bottom_row = mat[-1:, :]
    rest = mat[:-1, :].reshape((cols - 1, rows - 1))
    assert rest.shape == (rows - 2, cols - 1), f'{rest.shape=}'
    rest = np.rot90(rest.reshape(rows - 2, -1), k=3)
    left_col = mat[:, 0:1]
    rest = mat[:, :1]
    rest = np.rot90(rest, k=3)
    assert rest.shape == (rows - 2, cols - 2), f'{rest.shape=}'
    rest = spiral_visit(rest)

    rest = np.concatenate([left_col, rest], axis=1)
    rest = np.concatenate([rest, bottom_row], axis=0)
    rest = np.concatenate([rest, right_col], axis=1)
    rest = np.concatenate([top_row, rest], axis=0)
    return rest

In [33]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [34]:
spiral_visit(mat)

ValueError: cannot reshape array of size 72 into shape (8,8)

In [23]:
mat[:, -1:]

array([[ 8],
       [17],
       [26],
       [35],
       [44],
       [53],
       [62],
       [71],
       [80]])

In [25]:
mat[:, :-1].shape

(9, 8)