In [1]:
import numpy as np
import pandas as pd

In [43]:
items = np.array([(1, 4), (2, 5), (6, 7), (1, 5)])

In [44]:
items

array([[1, 4],
       [2, 5],
       [6, 7],
       [1, 5]])

In [45]:
value_per_unit_of_weight = np.apply_along_axis(lambda item: item[0] / item[1], axis=1, arr=items)

In [46]:
value_per_unit_of_weight

array([0.25      , 0.4       , 0.85714286, 0.2       ])

In [47]:
df = pd.DataFrame(items)

In [48]:
df

0  1
0  1  4
1  2  5
2  6  7
3  1  5

In [64]:
(
    df
    .assign(
        value_per_unit_of_weight=lambda d: d[0] / d[1]
    )
    .sort_values(by='value_per_unit_of_weight', ascending=False)
    .iloc[1:]
    .assign(
        cum_weight=lambda d: d[1].cumsum(),
        cum_weight_before=lambda d: d.cum_weight - d[1], 
        take=lambda d: np.where(d.cum_weight <= 7, 1, np.where(d.cum_weight_before < 7, (7 - d.cum_weight_before) / d[1], 0)),
        value=lambda d: d['take'] * d[0],
    )
    # ['value']
    # .sum()
)

0  1  value_per_unit_of_weight  cum_weight  cum_weight_before  take  value
1  2  5                      0.40           5                  0   1.0    2.0
0  1  4                      0.25           9                  5   0.5    0.5
3  1  5                      0.20          14                  9   0.0    0.0

In [85]:
col = np.array([[True, False] * 4]); row = col.T

In [86]:
col ^ row

array([[False,  True, False,  True, False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False],
       [False,  True, False,  True, False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False],
       [False,  True, False,  True, False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False],
       [False,  True, False,  True, False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False]])

In [87]:
my_mat = pd.DataFrame(np.zeros((8, 8)), columns=iter("ABCDEFGH"))

In [88]:
my_mat

A    B    C    D    E    F    G    H
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [89]:
s = my_mat.style

In [90]:
s.set_table_styles([  # create internal CSS classes
    {'selector': '.true', 'props': 'background-color: #e6ffe6;'},
    {'selector': '.false', 'props': 'background-color: #ffe6e6;'},
], overwrite=False)

In [91]:
to_str = lambda cell_val: 'true' if cell_val else 'false' 

to_str = np.vectorize(to_str)

to_str(col ^ row)

array([['false', 'true', 'false', 'true', 'false', 'true', 'false',
        'true'],
       ['true', 'false', 'true', 'false', 'true', 'false', 'true',
        'false'],
       ['false', 'true', 'false', 'true', 'false', 'true', 'false',
        'true'],
       ['true', 'false', 'true', 'false', 'true', 'false', 'true',
        'false'],
       ['false', 'true', 'false', 'true', 'false', 'true', 'false',
        'true'],
       ['true', 'false', 'true', 'false', 'true', 'false', 'true',
        'false'],
       ['false', 'true', 'false', 'true', 'false', 'true', 'false',
        'true'],
       ['true', 'false', 'true', 'false', 'true', 'false', 'true',
        'false']], dtype='<U5')

In [92]:
s.set_td_classes(pd.DataFrame(to_str(col ^ row), columns=iter("ABCDEFGH")))

In [93]:
xx, yy = np.meshgrid(range(8), range(8))

In [98]:
xx

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]])

In [99]:
yy

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [95]:
(xx + yy) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [96]:
to_str((xx + yy) % 2)

array([['false', 'true', 'false', 'true', 'false', 'true', 'false',
        'true'],
       ['true', 'false', 'true', 'false', 'true', 'false', 'true',
        'false'],
       ['false', 'true', 'false', 'true', 'false', 'true', 'false',
        'true'],
       ['true', 'false', 'true', 'false', 'true', 'false', 'true',
        'false'],
       ['false', 'true', 'false', 'true', 'false', 'true', 'false',
        'true'],
       ['true', 'false', 'true', 'false', 'true', 'false', 'true',
        'false'],
       ['false', 'true', 'false', 'true', 'false', 'true', 'false',
        'true'],
       ['true', 'false', 'true', 'false', 'true', 'false', 'true',
        'false']], dtype='<U5')

In [97]:
s.set_td_classes(pd.DataFrame(to_str((xx + yy) % 2), columns=iter("ABCDEFGH")))